- hosts: db_servers
  remote_user: ubuntu
  become: true
  gather_facts: yes
  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        name: "*"
        state: latest

    - name: Set Hostname
      hostname: 
        name: "{{ inventory_hostname }}"

    - name: Install dependencies
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg2
          - lsb-release
          - python3-pip
          - python3-dev
          - default-libmysqlclient-dev
          - build-essential
      
    - name: Install pymysql
      pip:
        name: pymysql
        state: present
    
    - name: Add Percona repo
      apt:
        deb: "https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release }}_all.deb"

    - name: Set Percona dist
      shell: percona-release setup ps80

    - name: Install Percona
      apt: name=percona-server-server state=present update_cache=yes

    - name: Copy conf file
      template:
        src: templates/mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        owner: root
        group: root
        mode: 0644

    - name: Restart DB
      systemd:
        name: mysql
        state: restarted
