- hosts: dbreplica
  remote_user: ubuntu
  become: true
  gather_facts: yes
  vars_files:
    - vars/secrets
  tasks:
    - name: Stop replication
      mysql_replication: 
        mode: stopslave
        login_user: root
        login_password: ""
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Configure replication
      mysql_replication:
        mode: changemaster
        login_user: root
        login_password: ""
        login_unix_socket: /var/run/mysqld/mysqld.sock
        master_host: "{{ dbmaster_private_ip }}"
        master_user: replica
        master_password: "{{ mysql_root_password }}"
        master_log_file: "{{ Master_File }}"
        master_log_pos: "{{ Master_Position }}"

    - name: Start replication
      mysql_replication: 
        mode: startslave
        login_user: root
        login_password: ""
        login_unix_socket: /var/run/mysqld/mysqld.sock